#!/bin/sh

# Source xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Statusbar loop
while true; do
    xsetroot -name " $(date +"%a %F %R") | $(cat /sys/class/power_supply/BAT0/capacity) % "
    sleep 5s
done &

# Normal launch
compton -b &
exec dwm

# With dbus
#compton -b &
#dbus-update-activation-environment --all
#dbus-launch ssh-agent dwm
