#!/bin/sh

# Source xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Normal launch
#compton -b &
#fehwallpaper & # This isnt done here anymore
#exec dwm

# With dbus
compton -b &
dbus-update-activation-environment --all
dbus-launch ssh-agent dwm
