#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# startx/xinit also sources this file.

# xrandr --dpi 96 	# Set DPI?
# IMPLEMENT hostcheck + z10xrandr
xset r rate 200 50 	# Set the keyboard repeat delay and rate
#fehwallpaper &		# set background here aswell?
xwallpaper --zoom ~/.local/share/wallpaper &
