#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# startx/xinit also source this file.

# xrandr --dpi 96 	# Set DPI?
xset r rate 150 75 	# Set the keyboard repeat delay and rate
#fehwallpaper &		# set background here aswell?
xwallpaper --zoom ~/.local/share/wallpaper &
